[project]
name = "pai-shadow-spectroscopy"
version = "0.1.0"
description = "Energy Gap Estimation of Hamiltonian by using Probabilistic Angle Interpolation and Shadow Spectroscopy"
authors = [{ name = "Pages Hugo", email = "hugo.pages@etu.unistra.fr" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "matplotlib==3.9.2",
    "multiprocess==0.70.17",
    "numba==0.60.0",
    "qiskit>=1.2.4,<2",
    "qiskit-aer==0.15.1",
    "qiskit-ibm-runtime==0.31.0",
    "scipy==1.14.1",
    "tqdm==4.66.5",
    "statsmodels>=0.14.4,<0.15",
]

[project.urls]
homepage = "https://github.com/hugopgs/Frontier_Lab"
repository = "https://github.com/hugopgs/Frontier_Lab"

[dependency-groups]
test = ["pytest>=8.3.5,<9"]

[tool.uv]
package = false
